### ISSUE TITLE
Missing fields 

### ISSUE THREAD

**Issue by LiamOConnorHobbs** [simesy/lecapi#65]
The production site is missing some fields required to move the content across.
We need the fields 
- Language
- Summary 
- Tags
- Media
- Avatar
<img width="344" alt="Screen Shot 2020-12-02 at 12 29 45 pm" src="https://user-images.githubusercontent.com/67258039/100816394-15c87a00-349a-11eb-8164-f81099fac7a0.png">
<img width="438" alt="Screen Shot 2020-12-02 at 12 29 38 pm" src="https://user-images.githubusercontent.com/67258039/100816399-16f9a700-349a-11eb-9998-48c14a0755a4.png">
<img width="891" alt="Screen Shot 2020-12-02 at 12 29 28 pm" src="https://user-images.githubusercontent.com/67258039/100816400-182ad400-349a-11eb-9a4e-949f1789eb0e.png">
<img width="160" alt="Screen Shot 2020-12-02 at 12 29 21 pm" src="https://user-images.githubusercontent.com/67258039/100816402-18c36a80-349a-11eb-99de-fb876a276354.png">

**Comment by febdao** [comment]
@LiamOConnorHobbs could you please add the `Summary` field into article contentype?

**Comment by febdao** [comment]
![Screen Shot 2020-12-09 at 10 43 44 am](https://user-images.githubusercontent.com/7425119/101554801-76603580-3a0b-11eb-9397-3dc34826d837.png)

Never mind, @LiamOConnorHobbs 
I believe that it is `Desk` field :D
